services:
  - type: web
    name: sekolahpintar-api
    runtime: node
    repo: https://github.com/ibnzxz/sekolahpintar
    plan: free
    buildCommand: npm install && npx prisma generate --schema=packages/db/prisma/schema.prisma && npm run build:api
    startCommand: npx prisma migrate deploy --schema=packages/db/prisma/schema.prisma && node apps/api/dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://sekolahpintar.vercel.app
